In [1]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api

this model is trained over the google news data

the dimesion of this model(number of neuron in hidden layer)=300

news--> crimial

In [ ]:
#skim gram
model = api.load("word2vec-google-news-300")

In [3]:
model["sunny"]

array([ 1.59179688e-01,  1.07910156e-01,  3.71093750e-02,  1.61132812e-01,
        3.02734375e-01, -3.35937500e-01, -3.83300781e-02, -1.32751465e-03,
       -8.69140625e-02,  2.25585938e-01,  2.23388672e-02,  1.35742188e-01,
       -1.04003906e-01,  1.73828125e-01,  5.46875000e-02,  1.13769531e-01,
       -1.53320312e-01,  2.29492188e-01,  1.13769531e-01,  1.61132812e-02,
       -1.46484375e-01,  5.07812500e-01, -1.08886719e-01, -1.59179688e-01,
       -9.37500000e-02, -6.64062500e-02,  1.90429688e-01,  2.49023438e-01,
       -1.08398438e-01,  2.00195312e-01, -2.19726562e-01,  8.83789062e-02,
        4.98046875e-02,  4.27246094e-02, -3.02734375e-01, -1.64062500e-01,
       -9.86328125e-02, -2.61718750e-01,  1.49414062e-01,  2.12890625e-01,
        2.38281250e-01, -1.50390625e-01,  1.82617188e-01,  1.18408203e-02,
        1.85546875e-02, -1.41601562e-01, -1.41601562e-01,  3.14941406e-02,
       -2.50000000e-01,  2.55859375e-01,  2.53906250e-01,  3.69140625e-01,
        4.43359375e-01,  

In [4]:
len(model["sunny"])

300

In [6]:
model["i am sunny"]

KeyError: "Key 'i am sunny' not present"

In [7]:
model["men"]

array([-4.78515625e-02,  1.66992188e-01,  7.81250000e-02,  2.10571289e-03,
        2.25585938e-01, -2.25585938e-01, -2.09960938e-01, -3.73535156e-02,
       -1.85546875e-02,  1.94335938e-01, -3.00292969e-02, -1.77734375e-01,
        5.20019531e-02,  1.33789062e-01, -1.13769531e-01,  1.10351562e-01,
       -3.27148438e-02,  2.89916992e-03,  9.88769531e-03,  9.27734375e-02,
       -2.19726562e-01, -2.47802734e-02, -8.59375000e-02, -2.67578125e-01,
       -2.51464844e-02, -2.55859375e-01, -1.61132812e-01,  2.53906250e-01,
        5.24902344e-02, -1.00097656e-02,  1.82617188e-01,  7.61718750e-02,
       -1.60980225e-03, -3.10058594e-02, -3.32031250e-02,  1.81640625e-01,
       -3.88183594e-02, -1.83593750e-01, -8.64257812e-02,  2.20703125e-01,
       -7.11059570e-03,  8.60595703e-03,  1.73828125e-01, -9.27734375e-02,
        1.25000000e-01, -1.28906250e-01, -4.85839844e-02, -1.21093750e-01,
        8.00781250e-02,  1.05957031e-01,  1.42578125e-01,  6.78710938e-02,
        6.29882812e-02, -

In [8]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [9]:
model.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [10]:
model.similarity("man","woman")

0.76640123

In [11]:
model.similarity("man","python")

0.2097966

In [12]:
model.similarity("man","man")

1.0

In [13]:
model.similarity("happy","joy")

0.35500747

In [14]:
model.similarity('python','java')

0.12539075

In [15]:
model.similarity('sunny','sunny')

1.0

In [16]:
model.similarity('sunny','Sunny')

0.43010473

In [17]:
model.doesnt_match(["PHP","JAVA","DOG","C++"])

'DOG'

In [18]:
vec=model['king'] - model['man'] + model['woman']

In [19]:
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

## average wrod2vec

In [ ]:
sentence = " I love machine learning"

sentece -> vector?

averge Word2Vec

first -> create a vector for each word in the sentence

then -> take the average of all the vectors to get a single vector representation for the entire sentence   

In [ ]:
sentence = " I love machine learning"
sentence1 = "I love to sit near river bank"
sentence2 = "I always deposite money in bank"

In [ ]:
#STATICS VECTOR
bank=[1,2,3]

In [ ]:
sentence1-> []

In [ ]:
sentence2 ->

In [ ]:
CHATGPT->

HI HOW ARE YOU BUDDY?

YOU ARE ASKING

I AM AKSING?

In [21]:
sentence.lower().split()

['i', 'love', 'machine', 'learning']

In [23]:
words = sentence.lower().split()

In [22]:
word_vectors = []

In [25]:
for word in words:
    print(word)
    word_vectors.append(model[word])
    

i
love
machine
learning


In [26]:
word_vectors

[array([-2.25585938e-01, -1.95312500e-02,  9.08203125e-02,  2.37304688e-01,
        -2.92968750e-02,  9.32617188e-02, -5.88378906e-02, -4.10156250e-02,
         5.22460938e-02,  2.00195312e-02, -3.44238281e-02, -2.91015625e-01,
        -2.61718750e-01, -1.90429688e-01,  3.85742188e-02,  8.30078125e-03,
         3.14941406e-02,  7.47070312e-02,  1.14746094e-01,  1.24511719e-02,
        -2.11914062e-01,  1.28906250e-01,  2.55859375e-01,  1.08886719e-01,
        -7.03125000e-02,  1.60156250e-01, -4.00390625e-01, -1.16699219e-01,
        -3.22265625e-02, -6.73828125e-02,  1.55273438e-01,  1.25000000e-01,
        -6.22558594e-02,  3.56445312e-02, -1.79687500e-01,  1.58203125e-01,
        -2.53906250e-01,  1.74804688e-01, -1.18164062e-01, -2.19726562e-03,
         1.49536133e-02, -5.71289062e-02,  2.39257812e-01,  1.36718750e-01,
         1.47460938e-01,  7.08007812e-02,  1.72851562e-01, -2.38281250e-01,
        -5.71289062e-02, -1.04492188e-01,  2.23388672e-02,  8.74023438e-02,
         1.4

In [29]:
import numpy as np
sentence_vector =  np.mean(word_vectors,axis=0)

In [30]:
sentence_vector

array([ 1.12304688e-02, -1.13830566e-02,  2.06909180e-02,  1.43615723e-01,
       -3.96728516e-02,  1.39282227e-01,  5.63964844e-02, -2.90527344e-02,
       -1.94091797e-02,  6.54907227e-02,  9.49096680e-03, -1.30126953e-01,
       -1.07116699e-01, -1.29760742e-01,  9.94873047e-03,  7.73925781e-02,
       -4.68139648e-02,  1.51245117e-01,  1.24572754e-01, -1.01013184e-01,
       -7.25708008e-02,  1.22924805e-01,  7.96489716e-02,  1.19506836e-01,
        5.38940430e-02, -4.02832031e-02, -1.22619629e-01, -2.44140625e-04,
        2.44140625e-02, -1.11328125e-01,  1.31835938e-02, -3.17382812e-03,
       -5.45196533e-02,  1.23840332e-01, -6.40258789e-02, -2.56347656e-03,
       -2.30255127e-02,  9.41162109e-02,  3.81469727e-02,  3.29589844e-02,
        1.39480591e-01, -7.67211914e-02,  1.08428955e-01,  3.95202637e-02,
        6.39648438e-02, -6.82373047e-02,  8.05664062e-02,  5.64575195e-02,
       -3.21960449e-02,  4.71801758e-02, -4.17327881e-02,  7.21435547e-02,
       -4.82177734e-03,  

In [31]:
sentence_vector.shape

(300,)

In [ ]:
word2vec -> every word into the KeyedVectors

avg word2vec -> every sentence into a vector

now this technique is old, 

will see the sota(transformer based tech in next class)

In [32]:
model

In [33]:
model["chatGPT"]

KeyError: "Key 'chatGPT' not present"

In [34]:
model["sunny"]

array([ 1.59179688e-01,  1.07910156e-01,  3.71093750e-02,  1.61132812e-01,
        3.02734375e-01, -3.35937500e-01, -3.83300781e-02, -1.32751465e-03,
       -8.69140625e-02,  2.25585938e-01,  2.23388672e-02,  1.35742188e-01,
       -1.04003906e-01,  1.73828125e-01,  5.46875000e-02,  1.13769531e-01,
       -1.53320312e-01,  2.29492188e-01,  1.13769531e-01,  1.61132812e-02,
       -1.46484375e-01,  5.07812500e-01, -1.08886719e-01, -1.59179688e-01,
       -9.37500000e-02, -6.64062500e-02,  1.90429688e-01,  2.49023438e-01,
       -1.08398438e-01,  2.00195312e-01, -2.19726562e-01,  8.83789062e-02,
        4.98046875e-02,  4.27246094e-02, -3.02734375e-01, -1.64062500e-01,
       -9.86328125e-02, -2.61718750e-01,  1.49414062e-01,  2.12890625e-01,
        2.38281250e-01, -1.50390625e-01,  1.82617188e-01,  1.18408203e-02,
        1.85546875e-02, -1.41601562e-01, -1.41601562e-01,  3.14941406e-02,
       -2.50000000e-01,  2.55859375e-01,  2.53906250e-01,  3.69140625e-01,
        4.43359375e-01,  

In [35]:
model.most_similar("sunny")

[('balmy', 0.7314587831497192),
 ('sunshine', 0.7251086831092834),
 ('overcast', 0.6918097734451294),
 ('breezy', 0.6885849237442017),
 ('gloriously_sunny', 0.6779158711433411),
 ('sunny_skies', 0.6688455939292908),
 ('chilly', 0.66850346326828),
 ('seasonably_cool', 0.6619703769683838),
 ('windy', 0.6603769659996033),
 ('drizzly', 0.6585174202919006)]