In [1]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [2]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\Sunny\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\Sunny\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\Sunny\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\Sunny\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\Sunny\AppData\Roaming\nltk_data...
[

True

In [3]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [4]:
for file in os.listdir('./data/'):
    print(file)

story1.txt
story2.txt


In [5]:
f = open(r"D:\complete_content_new\Full-Stack-GenAI-Bootcamp-1.0\Class-06-07-11-12-Apr-Word2vec-with-practical\data\story1.txt",encoding='unicode_escape')

In [6]:
f

<_io.TextIOWrapper name='D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-06-07-11-12-Apr-Word2vec-with-practical\\data\\story1.txt' mode='r' encoding='unicode_escape'>

In [7]:
corpus =f.read()

In [8]:
corpus

'Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers. He was very curious about how things worked and always asked questions. His parents often smiled at his curiosity and encouraged him to learn more.\n\nEvery day after school, Arjun would sit with his books and explore different topics. He was especially fascinated by science and technology. He wanted to understand how machines think and whether they could become as intelligent as humans.\n\nOne day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence. He read about how machines can learn from data, recognize patterns, and even make decisions. This idea completely amazed him.\n\nHe started imagining a future where machines could help humans solve complex problems. That day, he made a decision that he wanted to become an AI engineer.\n\nArjun began learning programming using free resources. At first, everything seemed difficu

In [9]:
sent_tokenize(corpus)

['Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers.',
 'He was very curious about how things worked and always asked questions.',
 'His parents often smiled at his curiosity and encouraged him to learn more.',
 'Every day after school, Arjun would sit with his books and explore different topics.',
 'He was especially fascinated by science and technology.',
 'He wanted to understand how machines think and whether they could become as intelligent as humans.',
 'One day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence.',
 'He read about how machines can learn from data, recognize patterns, and even make decisions.',
 'This idea completely amazed him.',
 'He started imagining a future where machines could help humans solve complex problems.',
 'That day, he made a decision that he wanted to become an AI engineer.',
 'Arjun began learning programming using free resources.',


In [10]:
raw_sent = sent_tokenize(corpus)

In [11]:
for i in raw_sent:
  print(simple_preprocess(i))

['once', 'upon', 'time', 'there', 'was', 'young', 'boy', 'named', 'arjun', 'who', 'lived', 'in', 'small', 'town', 'surrounded', 'by', 'hills', 'and', 'rivers']
['he', 'was', 'very', 'curious', 'about', 'how', 'things', 'worked', 'and', 'always', 'asked', 'questions']
['his', 'parents', 'often', 'smiled', 'at', 'his', 'curiosity', 'and', 'encouraged', 'him', 'to', 'learn', 'more']
['every', 'day', 'after', 'school', 'arjun', 'would', 'sit', 'with', 'his', 'books', 'and', 'explore', 'different', 'topics']
['he', 'was', 'especially', 'fascinated', 'by', 'science', 'and', 'technology']
['he', 'wanted', 'to', 'understand', 'how', 'machines', 'think', 'and', 'whether', 'they', 'could', 'become', 'as', 'intelligent', 'as', 'humans']
['one', 'day', 'while', 'browsing', 'through', 'an', 'old', 'computer', 'at', 'school', 'arjun', 'discovered', 'the', 'concept', 'of', 'artificial', 'intelligence']
['he', 'read', 'about', 'how', 'machines', 'can', 'learn', 'from', 'data', 'recognize', 'patterns',

In [12]:
folder_path = r"D:\complete_content_new\Full-Stack-GenAI-Bootcamp-1.0\Class-06-07-11-12-Apr-Word2vec-with-practical\data"
story = []
for filename in os.listdir(folder_path):
  file_path=os.path.join(folder_path,filename)
  with open(file_path,encoding='unicode_escape') as f:
    corpus=f.read()
  raw_sent=sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [13]:
story

[['once',
  'upon',
  'time',
  'there',
  'was',
  'young',
  'boy',
  'named',
  'arjun',
  'who',
  'lived',
  'in',
  'small',
  'town',
  'surrounded',
  'by',
  'hills',
  'and',
  'rivers'],
 ['he',
  'was',
  'very',
  'curious',
  'about',
  'how',
  'things',
  'worked',
  'and',
  'always',
  'asked',
  'questions'],
 ['his',
  'parents',
  'often',
  'smiled',
  'at',
  'his',
  'curiosity',
  'and',
  'encouraged',
  'him',
  'to',
  'learn',
  'more'],
 ['every',
  'day',
  'after',
  'school',
  'arjun',
  'would',
  'sit',
  'with',
  'his',
  'books',
  'and',
  'explore',
  'different',
  'topics'],
 ['he',
  'was',
  'especially',
  'fascinated',
  'by',
  'science',
  'and',
  'technology'],
 ['he',
  'wanted',
  'to',
  'understand',
  'how',
  'machines',
  'think',
  'and',
  'whether',
  'they',
  'could',
  'become',
  'as',
  'intelligent',
  'as',
  'humans'],
 ['one',
  'day',
  'while',
  'browsing',
  'through',
  'an',
  'old',
  'computer',
  'at',
  'sc

In [14]:
len(story)

44

In [15]:
story[0]

['once',
 'upon',
 'time',
 'there',
 'was',
 'young',
 'boy',
 'named',
 'arjun',
 'who',
 'lived',
 'in',
 'small',
 'town',
 'surrounded',
 'by',
 'hills',
 'and',
 'rivers']

In [30]:
story[1]

['he',
 'was',
 'very',
 'curious',
 'about',
 'how',
 'things',
 'worked',
 'and',
 'always',
 'asked',
 'questions']

In [ ]:
sunny->100
Divyansh->6
Rahul->3

In [ ]:
# Word2Vec(..., sg=0)  # CBOW #by default
# Word2Vec(..., sg=1)  # Skip-gram

In [ ]:
# custom_model =gensim.models.Word2Vec(
#     window=10,
#     min_count=5,
#     vector_size=150
    
# )

## these all the value are the hyperparameter

In [26]:
custom_model =gensim.models.Word2Vec(
    window=10,
    min_count=1,
    vector_size=150
    
)

In [27]:
custom_model.build_vocab(story)

In [44]:
len(custom_model.wv.index_to_key)

257

In [28]:
custom_model.corpus_count

44

In [45]:
custom_model.corpus_count

44

In [29]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=10)

(3371, 5220)

In [30]:
custom_model.wv["arjun"]

array([ 0.0025617 ,  0.00281553,  0.00667763, -0.00304704, -0.00098525,
       -0.00483486, -0.00656261, -0.00558851, -0.00093259, -0.00410921,
        0.00337374, -0.00407432,  0.00142383,  0.0004671 , -0.00249849,
       -0.00087681,  0.0066964 ,  0.00607645, -0.00317123,  0.00625151,
       -0.0039475 ,  0.0039679 , -0.00167548,  0.00254897,  0.00204642,
        0.004445  , -0.00189752,  0.00562742,  0.00488234, -0.00665661,
       -0.0052223 , -0.0051106 ,  0.00169053, -0.00213649, -0.00483902,
       -0.00532992,  0.00603732,  0.00142346, -0.00622885, -0.00347193,
        0.00207329, -0.00311205,  0.00315924, -0.00295625,  0.00188825,
       -0.00539226,  0.00429895,  0.00311866,  0.00058397,  0.002016  ,
       -0.00580979,  0.00142071, -0.00068877, -0.00603753, -0.00627231,
       -0.00086464,  0.00299517,  0.00262293, -0.00438031, -0.00448252,
       -0.00351857, -0.00192492, -0.0049603 , -0.00648967, -0.00166109,
       -0.00566687, -0.00413151, -0.00406333, -0.00205244, -0.00

In [31]:
len(custom_model.wv["arjun"])

150

In [32]:
custom_model.wv["farmers"]

array([ 0.0025271 ,  0.00111317,  0.00191904,  0.00538546,  0.00442418,
        0.00240244,  0.00523134, -0.00472751,  0.00485109,  0.00278541,
       -0.00380337, -0.00278136,  0.00396342,  0.00386073, -0.00680806,
        0.00067508, -0.00021164,  0.00053407,  0.00455358, -0.00458701,
        0.00619607, -0.00627611,  0.00441338,  0.00661945, -0.00249096,
       -0.00639447,  0.00386062, -0.00618601, -0.00567506, -0.00078872,
       -0.0043589 ,  0.00581321,  0.0050518 ,  0.00029306,  0.00514941,
        0.00667842,  0.00389835,  0.00297057,  0.00364997,  0.00399388,
        0.00313769,  0.0042472 , -0.00525124,  0.00584923,  0.00563856,
        0.0061999 , -0.00586233, -0.0023642 , -0.00019196,  0.00279583,
       -0.00545618,  0.0001015 ,  0.00396681,  0.00655028, -0.00188664,
        0.00129072,  0.00428252, -0.00119235,  0.00130181, -0.00618425,
        0.00028083,  0.00268824,  0.00285098, -0.00664305, -0.0032896 ,
        0.00193203,  0.00099457, -0.00337131,  0.00350839,  0.00

In [33]:
custom_model.wv["ai"]

array([ 5.9823100e-03,  5.8570183e-03, -4.0939976e-03,  7.2821905e-04,
       -5.8869277e-03, -4.6581440e-03, -3.1703766e-03,  6.6279345e-03,
       -3.4645072e-03,  3.9472817e-03, -2.8877575e-03, -4.0149344e-03,
        5.3271512e-03,  2.6553578e-03, -2.1997509e-03,  4.8772423e-03,
        3.8540040e-03, -1.4713660e-03,  4.0054414e-03, -5.8491291e-03,
        1.5508347e-03, -6.1659184e-03,  4.0512925e-04, -6.0455105e-03,
       -1.4752175e-03,  6.1969720e-03,  1.9097923e-03,  1.1554671e-04,
       -4.3640579e-03, -6.5269410e-03,  4.5358590e-03, -6.1076395e-03,
        1.1089755e-03,  1.5399621e-03, -1.0035278e-03,  3.7673847e-03,
        2.3680504e-03,  5.1293257e-03,  3.4867751e-03, -5.2449047e-03,
       -2.4391159e-03, -1.5893014e-04, -2.6576940e-03, -3.1864168e-03,
        4.2004231e-03,  5.3510885e-03, -1.9153419e-03,  5.2048545e-03,
       -6.5196934e-03, -4.5165517e-03, -2.7610234e-03,  6.5748324e-03,
        1.0799228e-03,  5.2917848e-04,  3.9038474e-03,  5.2942345e-03,
      

In [34]:
custom_model.wv.most_similar("arjun")

[('important', 0.264736533164978),
 ('books', 0.2376011610031128),
 ('to', 0.22176983952522278),
 ('on', 0.20686215162277222),
 ('explore', 0.2035728543996811),
 ('better', 0.18910063803195953),
 ('lose', 0.1785641312599182),
 ('solving', 0.1644434630870819),
 ('through', 0.1643753945827484),
 ('model', 0.1631138175725937)]

In [35]:
custom_model.wv.most_similar("ai")

[('computer', 0.25201115012168884),
 ('decision', 0.24667498469352722),
 ('so', 0.2401130348443985),
 ('the', 0.17992402613162994),
 ('predictions', 0.14957891404628754),
 ('where', 0.1368499994277954),
 ('improving', 0.13583141565322876),
 ('is', 0.13113795220851898),
 ('rivers', 0.13046599924564362),
 ('everything', 0.1289535015821457)]

In [36]:
custom_model.wv.most_similar("engineer")

[('programs', 0.2385317087173462),
 ('lose', 0.2195308655500412),
 ('algorithms', 0.21495571732521057),
 ('practicing', 0.20005598664283752),
 ('who', 0.1644534021615982),
 ('from', 0.1642623394727707),
 ('in', 0.1638709157705307),
 ('curiosity', 0.1629614681005478),
 ('through', 0.15496230125427246),
 ('recognize', 0.15426163375377655)]

In [37]:
custom_model.wv.most_similar("data")

[('concept', 0.2540935277938843),
 ('years', 0.2423122525215149),
 ('lived', 0.2200397402048111),
 ('an', 0.21449539065361023),
 ('to', 0.21149885654449463),
 ('wanted', 0.20911771059036255),
 ('read', 0.19689981639385223),
 ('used', 0.19005164504051208),
 ('system', 0.18148857355117798),
 ('inspired', 0.18077869713306427)]

In [38]:
custom_model.wv.doesnt_match(["arjun", "engineer", "programming", "farmers"])

'farmers'

In [39]:
custom_model.wv.doesnt_match(["data", "model", "system", "river"])

'model'

In [40]:
custom_model.wv.doesnt_match(["weather", "crops", "farmers", "technology"])

'farmers'

In [ ]:
google-news-million of Artical
neural and llm -> data hungry

In [41]:
custom_model.wv.similarity("ai", "technology")

-0.043608334

In [42]:
custom_model.wv.similarity("arjun", "engineer")

-0.008780554

## Assignment for this week

## add more data
## train for more epoch
## and check the accuracy of model
## check the embedding dimesion also

## inshort play with all the parameter

In [ ]:
SOTA/ Transformer